name: Create certificate and upload it to the GCP cert manager secrets

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Needed to access the repo

jobs:
  upload-cert:
    runs-on: ubuntu-latest

    steps:
    - name: Generate self-signed certificate
      run: |
        openssl req -x509 -newkey rsa:2048 \
          -keyout private.key -out certificate.crt \
          -days 365 -nodes \
          -subj "/CN=example.com"
        cat certificate.crt private.key > cert.pem

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/448277070386/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-actions-sa@isentropic-card-466907-e1.iam.gserviceaccount.com"

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Enable Secret Manager API (optional, one-time)
      run: gcloud services enable secretmanager.googleapis.com

    - name: Create the secret if it doesn't exist
      run: |
        if ! gcloud secrets describe my-cert-secret; then
          gcloud secrets create my-cert-secret --replication-policy="automatic"
        fi

    - name: Upload certificate to Secret Manager
      run: gcloud secrets versions add my-cert-secret --data-file=cert.pem
